# Site settings
title: Hux Blog
header-img: img/home-bg.jpg
email: huxpro@gmail.com
description: "一生想做浪漫极客。@Hux黄玄的博客主页、个人网站, 知乎@黄玄／阿里@鬼栈／Front-End／UX Unicorn／Web &amp; Mobile Lover／Motion Design "
baseurl: ""
url: "http://huxpro.github.io"


# SNS settings
RSS: false
weibo_username:     huxpro
zhihu_username:     huxpro
github_username:    huxpro
#twitter_username:  huxpro
facebook_username:  huxpro


# Build settings
highlighter: pygments
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true      # if you want to customize anchor. check out line:129 of `post.html`

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM        # use Github Flavored Markdown !important


# Duoshuo settings
# please set your own DuoShuo account in `post.html` and `about.html`
useDuoshuo: true    # use both Comment and Share
useShare: true      # use Comment only. seeing the Share component is depend on Comment so we can NOT use share only.


# Todo: Analysis settings
# Please set your own analysis account in `head.html`(Baidu) and `default.html`(QQ)
useBaiduAnalysis: true
useTencentAnalysis: true
useGoogleAnalysis: true     # TODO


# Sidebar settings
sidebar: true
sidebar-feature-tags: true
sidebar-about-description: "写写代码，做做设计，看看产品。世界那么大，多玩玩看看。"
sidebar-avatar: /img/avatar-hux.jpg     # use absolute URL.

# Friends
friends: [
    {
        title: "天镶的博客",
        href: "http://lingyu.wang/"
    },{
        title: "Luke的自留地",
        href: "http://hmqk1995.github.io"
    },{
        title: "SmdCn's Blog",
        href: "http://blog.smdcn.net"
    }
]
