# Site settings
title: Hux Blog 
header-img: img/home-bg.jpg
email: huxpro@gmail.com
description: "一生想做浪漫极客。@Hux黄玄的博客主页、个人网站, 知乎@黄玄／阿里@鬼栈／Front-End／UX Unicorn／Web &amp; Mobile Lover／Motion Design "
baseurl: ""
url: "http://huxpro.github.io"
twitter_username: huxpro
github_username:  huxpro
facebook_username:  huxpro
weibo_username: huxpro
zhihu_username: huxpro

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
