# Site settings
title: YUX I/O
SEOTitle: YUX的博客 | YUX Blog
header-img: img/home-bg.jpg
email: yu.xiao.fr@gmail.com
description: "关于Python与摄影、数学与思考 | YUX I/O - Mathématiques | 这里是 @YUX 的个人博客，与你一起发现更大的世界。"
keyword: "YUX, XIAO Yu, YUX I/O, XIAO Yu Photography, Python, MasterWatson, YUX Blog, 博客, 个人网站, 互联网, 数学, 巴黎, UPMC"
url: "http://yux.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username:     MasterWatson
zhihu_username:     YUX-IO
github_username:    YUX-IO
twitter_username:   shaw_yu
#facebook_username:  huxpro



# Build settings
highlighter: pygments
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
duoshuo_username: YUX
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
ga_track_id: 'UA-70427026-1'            # Format: UA-xxxxxx-xx
ga_domain: yux.io



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Fun is boring."
sidebar-avatar: /img/avatar-yux.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "天镶的博客",
        href: "http://lingyu.wang/"
    },{
        title: "Luke的自留地",
        href: "http://hmqk1995.github.io"
    },{
        title: "SmdCn's Blog",
        href: "http://blog.smdcn.net"
    },{
        title: "解旻的博客",
        href: "http://xieminis.me/"
    },{
        title: "DHong Say",
        href: "http://dhong.co"
    },{
        title: "尹峰以为",
        href: "http://ingf.github.io/"
    }
]
